### ISSUE TITLE
`python-pip` is no longer available. Fix build process.

### ISSUE THREAD

**Issue by forevermatt** [silinternational/developer-portal#194]
@mtompset - Is this something you already know how to fix? Don't let this pull you away from higher priorities, though.

Here was the error message:
```
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
```

**Comment by mtompset** [comment]
Installing python3-pip should install an alternative pip link to pip3, which is the newest version. Minor tweak in the Dockerfile, I believe.
